#ifndef _FCASTLOADER_H__
#define _FCASTLOADER_H__

enum 
{
	CAST_LOADER = 10000,
	CAST_IMPORT_CONSTRAINTS = 10001,
	CAST_IMPORT_IK_HANDLES = 10002,
	CAST_IMPORT_BIND_SKIN = 10003,
	CAST_IMPORT_GROUP
};
#endif

