CONTAINER fcastloader
{
	INCLUDE Fbase;
	NAME fcastloader;
	
	GROUP CAST_IMPORT_GROUP
	{
		DEFAULT 1;
		
		BOOL CAST_IMPORT_BIND_SKIN {}
		BOOL CAST_IMPORT_IK_HANDLES {}
		BOOL CAST_IMPORT_CONSTRAINTS {}
	}
}